import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../css/globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <main className="w-full flex flex-col items-center justify-start min-h-screen">
            {children}
          </main>
        </Theme>
      </body>
    </html>
  );
}
